# Generated by Django 3.2.9 on 2021-12-05 13:46

from django.db import migrations, models
import django.db.models.deletion
import formConsult.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], max_length=1)),
                ('especialidad', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.DateTimeField(verbose_name='disponibilidad')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formConsult.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, validators=[formConsult.validators.validate_rut])),
                ('edad', models.IntegerField(validators=[formConsult.validators.validate_age])),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], max_length=1)),
                ('email', models.EmailField(max_length=200)),
                ('fecha_consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formConsult.horario')),
                ('nombre_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formConsult.doctor')),
            ],
        ),
    ]
