# Generated by Django 3.2.9 on 2021-12-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formConsult', '0002_horario_estadisponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formConsult.doctor')),
                ('horarios', models.ManyToManyField(to='formConsult.Horario')),
            ],
        ),
    ]
