# Generated by Django 3.2.9 on 2021-12-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formConsult', '0003_doctor_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor_Horario',
        ),
    ]
