# Generated by Django 3.2.9 on 2021-12-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formConsult', '0004_delete_doctor_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='horario',
            name='fecha',
            field=models.DateField(null=True, verbose_name='fecha'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora',
            field=models.TimeField(null=True, verbose_name='hora'),
        ),
    ]
